services:
  - type: web
    name: trustchain-api
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: trustchain
      - key: SQUAD_SECRET_KEY
        sync: false
      - key: SQUAD_PUBLIC_KEY
        sync: false
      - key: SQUAD_MERCHANT_ID
        sync: false
      - key: SQUAD_BASE_URL
        value: https://sandbox-api-d.squadco.com
      - key: DEBUG
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11.9"
